### PR TITLE
Lexographically smallest after a swap

### PR DESCRIPTION
**Pull request by meetmukul1993**
## Title of the problem 
[3216. Lexicographically Smallest String After a Swap](https://leetcode.com/problems/lexicographically-smallest-string-after-a-swap/)

## Checklist before requesting a review
- [x] I have checked the [guide](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript#contributions) for contributions.
- [x] I have added the description at the top of the solution file.
- [x] I have added a test file for the problem.
- [x] I have added an entry to the [README](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript/blob/master/README.md) file with a link to the new file.
- [x] I have run linter (`npx eslint LeetcodeProblems LeetcodeProblemsTests`) and unit tests (`node Test.js`) and they pass. [More info](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript#run-tests).

Check the [guide](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript#contributions) and [this PR](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript/pull/39) example.

### CODE REVIEW

**Review by ignacio-chiazzo — APPROVED** [review]
Thanks!

**Review by ignacio-chiazzo — COMMENTED** [review]
Could you fix the linter issues by running `npx eslint LeetcodeProblems LeetcodeProblemsTests`

**Comment by meetmukul1993** [comment]
@ignacio-chiazzo updated the PR, can u please have a look again. Thanks

**Review by ignacio-chiazzo — APPROVED** [review]
Thanks

**Comment by meetmukul1993** [comment]
@ignacio-chiazzo Seems like the lint check runs after a maintainer approves it, earlier it failed, have updated the code again. can u please approve the lint execution

**Pull request merged**
